CREATE TABLE fact_orders (
    `Type` VARCHAR(50),
    `Days for shipping (real)` INT,
    `Days for shipment (scheduled)` INT,
    `Benefit per order` DECIMAL(10,2),
    `Sales per customer` DECIMAL(10,2),
    `Delivery Status` VARCHAR(50),
    `Late_delivery_risk` TINYINT,
    `Category Id` INT,
    `Category Name` VARCHAR(100),
    `Customer City` VARCHAR(100),
    `Customer Country` VARCHAR(100),
    `Customer Email` VARCHAR(150),
    `Customer Fname` VARCHAR(100),
    `Customer Id` INT,
    `Customer Lname` VARCHAR(100),
    `Customer Password` VARCHAR(255),
    `Customer Segment` VARCHAR(50),
    `Customer State` VARCHAR(100),
    `Customer Street` VARCHAR(255),
    `Customer Zipcode` VARCHAR(20),
    `Department Id` INT,
    `Department Name` VARCHAR(100),
    `Latitude` DECIMAL(10,6),
    `Longitude` DECIMAL(10,6),
    `Market` VARCHAR(100),
    `Order City` VARCHAR(100),
    `Order Country` VARCHAR(100),
    `Order Customer Id` INT,
    `order date (DateOrders)` DATETIME,
    `Order Id` INT,
    `Order Item Cardprod Id` INT,
    `Order Item Discount` DECIMAL(10,2),
    `Order Item Discount Rate` DECIMAL(10,2),
    `Order Item Id` INT PRIMARY KEY,
    `Order Item Product Price` DECIMAL(10,2),
    `Order Item Profit Ratio` DECIMAL(10,4),
    `Order Item Quantity` INT,
    `Sales` DECIMAL(10,2),
    `Order Item Total` DECIMAL(10,2),
    `Order Profit Per Order` DECIMAL(10,2),
    `Order Region` VARCHAR(100),
    `Order State` VARCHAR(100),
    `Order Status` VARCHAR(50),
    `Order Zipcode` VARCHAR(20),
    `Product Card Id` INT,
    `Product Category Id` INT,
    `Product Description` TEXT,
    `Product Image` VARCHAR(255),
    `Product Name` VARCHAR(255),
    `Product Price` DECIMAL(10,2),
    `Product Status` TINYINT,
    `shipping date (DateOrders)` DATETIME,
    `Shipping Mode` VARCHAR(50)
);